### ISSUE TITLE
Integer multiplication done before float conversion

### ISSUE THREAD

**Issue by whatyouknowaboutme** [facebookresearch/videoalignment#2]
In `class TemporalMatchKernel`:
`self.ms = (2 * np.pi * torch.arange(0, self.m)).float()` performs integer multiplication, to preserve float you could do:
`self.ms = (2 * np.pi * torch.arange(0, self.m).float())`

**Comment by LowikC** [comment]
Nice catch!
I will fix it. Thank you!
